function Inversiones() {
    return (
        <section className="padded">
            <div className="container">
                <h2>Inversiones</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident voluptas dolorum neque porro cupiditate illum laborum quam molestias veritatis blanditiis consequatur, optio sed aliquam officiis nam quibusdam fugit expedita eaque aspernatur veniam, et praesentium. Perspiciatis tempore quos aut, esse commodi amet? Voluptate similique iste sit doloribus dolor labore debitis quo totam. Recusandae expedita incidunt reiciendis magni facilis iusto ad, id natus blanditiis optio exercitationem aperiam quidem repellendus fugiat culpa veritatis ea est nulla cum eos facere distinctio. Sed, obcaecati commodi.</p>
                <p>Deserunt dolor molestias, corrupti asperiores eaque hic facere sapiente maxime eligendi cum a, nam modi laborum aut rem perspiciatis facilis temporibus repellat totam! Iste dolorum id necessitatibus exercitationem porro error dolore natus magnam inventore, aliquam fugit quam quo obcaecati sunt itaque, nesciunt reprehenderit culpa! Deserunt minima dolorum veniam rem asperiores a ipsa! Commodi, possimus dolorem reiciendis neque fuga odit. Inventore alias esse a, harum nostrum cum dicta assumenda. Recusandae necessitatibus, beatae delectus quae ipsum adipisci fugiat odio quaerat qui exercitationem!</p>
                <p>At quasi, cumque exercitationem amet maiores quibusdam provident fuga sequi minima corporis dolorum ex. Corporis autem nostrum ut, nemo quo nam aut odit enim adipisci harum id est numquam dicta soluta culpa reiciendis in dolore magnam libero aliquid! Voluptas nihil omnis odit eius! Pariatur natus repudiandae sapiente nesciunt labore consequatur, doloribus repellat mollitia incidunt animi nemo laboriosam deserunt fuga. Distinctio mollitia at provident iste et non harum molestias, repudiandae aliquam! Qui cupiditate nulla harum, ducimus cum placeat magnam voluptatum est!</p>
                <p>Cupiditate voluptas eos rem inventore? Dignissimos optio, laudantium aut dolorum blanditiis, perspiciatis officiis rem, facilis corrupti eum distinctio sint ut temporibus ipsum quas modi quo ea quidem molestiae. Cupiditate omnis enim necessitatibus asperiores tempora cum ut laboriosam et quas distinctio inventore fugit consequatur consectetur debitis doloribus nihil, eaque est ipsum quae ea illo praesentium maiores nisi! Explicabo voluptatum corporis possimus numquam nesciunt beatae perferendis, atque nulla modi, pariatur reiciendis. Dolores accusantium nesciunt odit provident tenetur totam rerum nobis est? Soluta.</p>
                <p>Autem eius in mollitia obcaecati dolorem ipsum maiores. Maiores aliquid consectetur libero repellendus quod voluptas maxime tempore ipsa dolore, error aliquam nesciunt, laborum, nisi numquam minus ex laboriosam possimus voluptate ducimus alias perferendis! Amet, eaque? Rem labore tempore nobis provident magnam iusto possimus odit dignissimos. Sunt voluptate labore nesciunt ex ab aliquam tempore ducimus quasi atque natus nostrum consequatur, aliquid amet sapiente. Facere velit ad vitae sint perferendis magni obcaecati sapiente temporibus repudiandae harum, delectus sit dolore aliquid optio ipsam.</p>
                <p>Ratione qui fugit quo velit atque aperiam natus delectus asperiores magnam sint perspiciatis beatae, est unde quaerat magni ab nisi voluptatum ut repudiandae officia? Quidem necessitatibus tempora aut dignissimos, incidunt impedit voluptatibus nam odit nostrum ratione veniam reiciendis sequi pariatur ullam nesciunt cum molestias modi soluta quaerat dicta optio ipsa quisquam tempore consequatur. Quia cum fugiat maxime perferendis delectus quibusdam quae consectetur animi quas, maiores ullam eligendi mollitia nesciunt obcaecati eos cupiditate? Nobis reprehenderit quasi molestiae dignissimos nemo nesciunt natus!</p>
            </div>
        </section>
    )
}

export default Inversiones